# Generated by Django 3.2.9 on 2021-11-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_det', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('image_name', models.CharField(max_length=20)),
                ('image_description', models.TextField(max_length=400)),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photos.category')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photos.location')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
